### ISSUE TITLE
Weird Windows Defender warnings Contebrew and Uwamson

### ISSUE THREAD

**Issue by Edgarhighmen** [Yeethan69/AIO#26]
Windows Defender is removing/disabling the file claiming it contains Contebrew.A!ml and Uwamson.A!ml , If I do anything other than "allow" those two components, the entire AIO gets removed. How should I handle this? Clicking Show details lists the AIO file.
![](https://i.gyazo.com/4ee87695669282a9ebfb370eb74bc910.png)

**Comment by ItsLogic** [comment]
If you are having problems I would add an exclusion to the exe following [these steps](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26) from the microsoft support website. Because of the way the tool behaves and is protected it gets flagged by windows defender and a few other AV programs so you need to exclude it if you dont want the warnings
