### ISSUE TITLE
Trojaner?

### ISSUE THREAD

**Issue by TheChxice** [Yeethan69/AIO#31]
Why exactly does the anti virus tell me that aio is a Trojaner?

**Comment by SilentBloody** [comment]
dont worry its safe, ive been using it since fh5 came out. im perfectly fine

**Comment by KKirschi** [comment]
With all the people (see downloads) using it, it should be safe and sound!

**Comment by LegitSoulja** [comment]
"Why exactly does the anti virus tell me that aio is a Trojaner?"

Because of obfuscation, it's hard for defender to decide rather this program is safe or not. Windows is unfamiliar with the program (signatures) each release, so it tries to keep you safe by preventing you from running unknown sources.

It's best to disable anti virus as it can also cause issues using such tools that calls native kernel functions that could be prevented by anti virus, making the cheat unfunctional.

**Comment by ItsLogic** [comment]
closing as its a false positive
