### ISSUE TITLE
Information on the FOV changer

### ISSUE THREAD

**Issue by daandupau** [Yeethan69/AIO#53]
I would like to know how the fov is changed. 
It works a bit too well :P  

it seems to be an offset that got changed. What kind of value is it? A float, 4 byte value? I tried finding it through cheat engine, but was unable to find the correct value to override. Could you share how the tool finds that value? 

Other thing it might be a good idea to add a integer field for the fov aswell so you can fine tune it. It now goes to black in cockpit view if you put the slider too low, putting higher al the way to max does not seem to change anything.

Thanks

**Comment by Yeethan69** [comment]
Sorry, but I will not be sharing how the FOV mod works, this is because it took me a long time to figure out and implement. This is one of the unique features that you wont find on other mod tools, and I would like to keep it this way as to make this tool all the more distinct.

I will take the number field idea into consideration, thanks.
